services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    expose:
      - '8000'
    volumes:
      - 'app_storage:/var/www/html/storage'
    networks:
      - coolify
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8000/up'
      interval: 30s
      timeout: 10s
      start_period: 180s
      retries: 5

volumes:
  app_storage: null

networks:
  coolify:
    external: true
